<?php
    echo "<h3>Hypotheek samenstellen</h3>";
    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"soortwoning\">Wat voor soort woning ga je kopen?</label>";
        echo "<select class=\"form-breedte75-procent text_input is_empty\" id=\"soortwoning\">";
        echo "<option value=\"bestaandewoning\">Bestaande woning</option>";
        echo "<option value=\"nieuwbouwwoning\">Nieuwbouw woning</option>";
        echo "<option value=\"bestaandappartement\">Bestaand appartement</option>";
        echo "<option value=\"nieuwbouwappartement\">Niewbouw appartement</option>";
        echo "</select>";
    echo "</div>";
    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"koopsom\">Koopsom van de woning</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"koopsom\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-koopsom-question\" />";
        echo "<div id=\"stap2-koopsom-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-koopsom-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Met de koopsom wordt het bedrag bedoelt waar je de woning voor hebt aangekocht. Dit bedrag staat ook vermeld in de koopovereenkomst. Koop je een nieuwbouwing vul dan het totaalbedrag invan de grondprijs en aanneemovereenkomst.";
        echo "<br />";
        echo "<br />";
        echo "Wens je een hypotheek met Nationale Hypotheek Garantie (NHG), let er dan op dat de maximale koopsom niet hoger zijn dan € 245.000,00.";
        echo "<br />";
        echo "<br />";
        echo "Heb je vragen bij het invullen van de koopsom? Onze hypotheekspecialisten helpen je graag verder.";
        echo "</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"verbouwen-ja-nee\">Wil je gaan verbouwen in de nieuwe woning?</label><br />";
        echo "<input type=\"radio\" name=\"verbouwen-ja-nee\" value=\"ja\">Ja<br />";
        echo "<input type=\"radio\" name=\"verbouwen-ja-nee\" value=\"nee\">Nee<br />";
        echo "<div id=\"verbouwen-ja\" style=\"display:none;\">";
            echo "Om te kunnen bepalen of je een bouwdepot mee kunt nemen in je aanvraag is het van belang dat je even gaat sparren met onze specialisten. Zij kunnen je vertellen of je dit kunt opgeven in de aanvraag. ";
            echo "<br />";
            echo "<br />";
            echo "<label for=\"verbouwingskosten\">Wat zijn de geschatte verbouwingskosten</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"verbouwingskosten\" />";
        echo "</div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"waardehuis\">Waarde van de woning</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"waardehuis\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-waardehuis-question\" />";
        echo "<div id=\"stap2-waardehuis-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-waardehuis-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Op dit moment mag je niet meer niet lenen dan 101% van de marktwaarde.Is je nieuwe woning al getaxeerd? Dan kun je de marktwaarde hier invullen. Weet je op dit moment niet de marktwaarde, vul dan hier ook de koopsom in.";
        echo "<br />";
        echo "<br />";
        echo "Bij nieuwbouw kun je hier het totaal van de grondprijs en aanneemovereenkomst invullen.";
        echo "</div></div>";
    echo "</div>";
    
    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"overdrachtsbelasting\">Overdrachtsbelasting</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"overdrachtsbelasting\" disabled=\"disabled\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-overdrachtsbelasting-question\" />";
        echo "<div id=\"stap2-overdrachtsbelasting-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-overdrachtsbelasting-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">Het percentage overdrachtsbelasting bedraagt op dit moment 2% van de koopsom.</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"leveringsakte-notaris\">Kosten leveringsakte notaris</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"leveringsakte-notaris\" value=\"800\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-leveringsakte-question\" />";
        echo "<div id=\"stap2-leveringsakte-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-leveringsakte-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Als de hypotheek helemaal rond is dan kun je naar de notaris om offcieel eigenaar te worden van je aangekochte woning. De kosten voor opmaken van de leveringsakte verschillen erg per notaris. Als koper mag jij bepalen waar je de akte gaat tekenen. Het is verstandig om de tarieven te vergelijken.";
        echo "<br />";
        echo "<br />";
        echo "Wij hebben een standaard bedrag van €800,00 ingevuld. Dit kun je zelf aanpassen.";
        echo "</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"hypotheekakte-notaris\">Kosten hypotheekakte notaris</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"hypotheekakte-notaris\" value=\"800\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-hypotheekakte-question\" />";
        echo "<div id=\"stap2-hypotheekakte-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-hypotheekakte-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Als de hypotheek helemaal rond is dan kun je naar de notaris om de hypotheekakte te tekenen, wij noemen dit passeren. Hiermee wordt de hypotheek definitief. De kosten voor opmaken van de hypotheekakteverschillen erg per notaris. Als koper mag jij bepalen waar je de akte gaat tekenen. Het is verstandig om de tarieven te vergelijken.";
        echo "<br />";
        echo "<br />";
        echo "Wij hebben een standaard bedrag van €800,00 ingevuld. Dit kun je zelf aanpassen.";
        echo "</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"taxatie\">Kosten taxatie</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"taxatie\" value=\"500\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-taxatie-question\" />";
        echo "<div id=\"stap2-taxatie-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-taxatie-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Als je een bestaande woning aankoopt moet de woning getaxeerd worden. De geldverstrekker wil weten of de koopsom marktconform is. Blijkt de taxatiewaarde onder de koopsom te liggen, dan betekend dit dat je meer eigen geld moet inleggen.";
        echo "<br />";
        echo "<br />";
        echo "De kosten voor de taxatie kunnen erg verschillen. Het is daarom verstandig de tarieven te vergelijken.";
        echo "</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"commissie\">Kosten Hypotheeklijn</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"commissie\" value=\"700\" disabled=\"disabled\" />";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-commissie-question\" />";
        echo "<div id=\"stap2-commissie-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-commissie-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Voor onze dienstverlening brengen wij een concurrenttarief van € 700,00 in rekening. Voor ondernemers geldt een tarief van € 850,00. Onze tarieven zijn transparant en er zijn adertjes onder het gras. Kijk voor meer informatie op: Veelgestelde vragen";
        echo "</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"rentevasteperiode\">Rentevaste periode</label>";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-rentevasteperiode-question\" />";
        echo "<div id=\"stap2-rentevasteperiode-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-rentevasteperiode-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "Heb je bepaald welke hypotheekvorm je wilt? Dan kun je daar nu een rentevaste periode bij kiezen. Ben je iemand die zekerheid zoekt, dan kan een langere termijn beter bij je passen, echter ligt de rente dan meestal wat hoger. Vind je zekerheid minder belangrijk en kun je schommelingen in je financiële situatie opvangen, dan kan een kortere periode zinvol zijn.";
        echo "</div></div>";
        echo "<select class=\"form-breedte75-procent text_input is_empty\" id=\"rentevasteperiode\" />";
            echo "<option value=\"1\">1</option>";
            echo "<option value=\"5\">5</option>";
            echo "<option value=\"10\" selected>10</option>";
            echo "<option value=\"20\">20</option>";
            echo "<option value=\"30\">30</option>";
        echo "</select>";

        // echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-commissie-question\" />";
        // echo "<div id=\"stap2-commissie-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-commissie-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        // $tekstStap2Commissie = $atts['stap2-commissie'] == '' ? 'stap2-commissie' : $atts['stap2-commissie'];
        // echo "<div style=\"padding:15px;\">".$tekstStap2Commissie."</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<label for=\"soorthypotheek\">Soort hypotheek</label>";
        echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-soorthypotheek-question\" />";
        echo "<div id=\"stap2-soorthypotheek-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-soorthypotheek-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        echo "<div style=\"padding:15px;\">";
        echo "<b>Annuïteitenhypotheek</b><br /><br>";
        echo "Bij een annuïteitenhypotheek betaal je -zolang de rente niet wordt aangepast -elke maand hetzelfde bruto bedrag. In het begin van de looptijd bestaat dit bedrag vooral uit rente, aan het einde van de looptijd vooral uit aflossing.";
        echo "<br />";
        echo "<br />";
        echo "Omdat de rente fiscaalaftrekbaar is, maar de aflossing niet, nemen de netto hypotheeklasten elk maand toe. Immers kun je gedurende de looptijd van je hypotheek steeds minder rente aftrekken, waardoor de netto maandlasten oplopen.";
        echo "<br />";
        echo "<br />";
        echo "<b>Lineaire hypotheek</b><br /><br>";
        echo "Bij de lineaire hypotheek los je, uitgaande van een looptijd van 30 jaar, elke maand 1/360 van de oorspronkelijke lening af. Naast de aflossing betaal je rente over de openstaande schuld.Hypotheekschuld daalt snel.";
        echo "<br />";
        echo "<br />";
        echo "Omdat je hypotheekschuld aan het begin van de looptijd het hoogstis, heb je in het begin ook de hoogte lasten. Hier staat tegenover dat je hypotheekschuld elkemaand een stukje kleiner wordt; je bruto én netto hypotheeklasten worden hierdoor dus ook elke maand iets lager. Omdat je de hypotheekschuld met een lineaire hypotheek snel omlaag brengt, is dit een zeer veilige hypotheekvorm.";
        echo "</div></div>";
        echo "<select class=\"form-breedte75-procent text_input is_empty\" id=\"soorthypotheek\" />";
            echo "<option value=\"\"></option>";
            echo "<option value=\"annuity\">Annuïteiten</option>";
            echo "<option value=\"linear\">Lineair</option>";
        echo "</select>";
        // echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-commissie-question\" />";
        // echo "<div id=\"stap2-commissie-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-commissie-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
        // $tekstStap2Commissie = $atts['stap2-commissie'] == '' ? 'stap2-commissie' : $atts['stap2-commissie'];
        // echo "<div style=\"padding:15px;\">".$tekstStap2Commissie."</div></div>";
    echo "</div>";

    echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "<div id=\"nhg-vraag\">";
            echo "<label for=\"nhg\">Wil je een hypotheek met Nationale Hypotheek Garantie?</label><br />";
            echo "<input type=\"radio\" name=\"nhg\" value=\"ja\">Ja<br />";
            echo "<input type=\"radio\" name=\"nhg\" value=\"nee\">Nee<br />";
            echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-nhg-question\" />";
            echo "<div id=\"stap2-nhg-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-nhg-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
            echo "<div style=\"padding:15px;\">";
            echo "Als de koopsom van jouw huislager is dan € 245.000,-, dan komt je in aanmerking voor Nationale Hypotheek Garantie (NHG). Een hypotheek met NHG biedt extra zekerheid voor de hypotheekverstrekker en in ruil hiervoor geeft de hypotheekverstrekker jou een lagere rente. Als de koopsom hoger is dan € 245.000,-, dan kom je niet aanmerking voor Nationale Hypotheek Garantie.";
            echo "<br />";
            echo "<br />";
            echo "Als je NHG wenst betaal je 1% kosten van de hypotheeksom aan NHG.";
            echo "</div></div>";
            echo "<div id=\"metNHG\" style=\"display:none;\">";
                echo "<label for=\"nhgkosten\">Kosten NHG</label><input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"nhgkosten\" disabled=\"disabled\" />";
            echo "</div><br />";
        echo "</div>";
    echo "</div>";

    // echo "<div class=\"first_form form_element form_fullwidth\">";
        echo "Hieronder zie je de aanbieders waar je een keuze uit kunt maken. Elke aanbieder hanteert andere voorwaarden. Om de voorwaarde te vergelijken, klik hier: <a href=\"http://www.ikregelzelfmijnhypotheek.nl/voorwaarden/\" target=\"_blank\">http://www.ikregelzelfmijnhypotheek.nl/voorwaarden/</a>";
        echo "<br />";
        echo "<div id=\"aanbieders\"></div>";
    // echo "</div>";
    
    echo "<table>";
        echo "<tr>";
            echo "<td>Leencapaciteit op basis van je loon</td>";
            echo "<td>";
                echo "<span id=\"result\"></span><span id=\"result-getal\" style=\"display:none;\"></span>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-leencapobvloon-question\" />";
                echo "<div id=\"stap2-leencapobvloon-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-leencapobvloon-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Dit is het bedrag wat je maximaal kunt lenen op het inkomen dat je hebt ingevuld van jou en je eventuele partner.";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Leencapaciteit op basis van de waarde van de woning</td>";
            echo "<td>";
                echo "<span id=\"max-hypotheek\"></span><span id=\"max-hypotheek-getal\" style=\"display:none;\"></span></td>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-leencapobvwoning-question\" />";
                echo "<div id=\"stap2-leencapobvwoning-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-leencapobvwoning-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Dit is het bedrag wat je kunt lenen op de marktwaarde van het huis. Op dit moment mag je maximaal 101% aan hypotheek hebben op de woning.";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Hoeveel hypotheek heb je nodig om je woning te kunnen financieren? </td>";
            echo "<td>";
                echo "<span id=\"benodigdehypotheek\"></span><span id=\"benodigdehypotheek-getal\" style=\"display:none;\"></span></td>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-hoeveelhypotheek-question\" />";
                echo "<div id=\"stap2-hoeveelhypotheek-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-hoeveelhypotheek-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Om de woning te kunnen kopen zie je hier het totaal staan van de koopsom, plus alle kosten.  Deze kosten worden ook wel de kosten koper genoemd.";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Dat betekent dat je aan eigen middelen moet inbrengen</td>";
            echo "<td>";
                echo "<span id=\"eigen-middelen-bedrag\"></span><span id=\"eigen-middelen-bedrag-getal\" style=\"display:none;\"></span></td>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-eigenmiddelen-question\" />";
                echo "<div id=\"stap2-eigenmiddelen-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-eigenmiddelen-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Omdat je maximale101% van de marktwaarde mag lenen is de kans groot dat je eigen geld moet inbrengen. De berekening laat zien hoeveel dit is om de woning te kunnen betalen. Dit bedrag moet op een spaarrekening staan. Als je een schenking ontvangtmag je dit geld ook gebruiken voor de hypotheek. ";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Wil je meer dan het verplichte bedrag inbrengen?</td>";
            echo "<td>";
                echo "<input class=\"form-breedte75-procent text_input is_empty\" type=\"number\" id=\"hoeveeleigengeld-getal\" /></td>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-eigenmiddelenzelf-question\" />";
                echo "<div id=\"stap2-eigenmiddelenzelf-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-eigenmiddelenzelf-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Wil je meer geld inleggen dan wat nodig is om de woning te kunnen kopen? Dan kun jedat hier invullen. Op deze manier verlaag je de hypotheek en dus ook de maandlasten. Je kunt spaargeld inleggen of gebruikmaken van een schenking.";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Jouw hypotheek wordt</td>";
            echo "<td>";
                echo "<span id=\"telenen\"></span><span id=\"telenen-getal\" style=\"display:none;\"></span></td>";
                echo "<img src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/help.png\" style=\"float:right; padding-top:5px; cursor: pointer;\" id=\"stap2-hypotheekbedrag-question\" />";
                echo "<div id=\"stap2-hypotheekbedrag-help\" style=\"clear:both; background-color:#dedede; display:none;\"><img id=\"stap2-hypotheekbedrag-kruis\" src=\"../wp-content/plugins/regel-zelf-uw-hypotheek/png/cross.png\" style=\"float:right; cursor: pointer;\" />";
                echo "<div style=\"padding:15px;\">";
                echo "Dit is het hypotheekbedrag waarvoor je een offerte aanvraagt.";
                echo "</div></div>";
            echo "</td>";
        echo "</tr>";
    echo "</table>";

    echo "<div id=\"orv-gegevens\" class=\"blauwe-rand\">";
        echo "<h3>Overlijdensrisicoverzekering</h3>";
        echo "<br />";
        echo "Je hebt een hypotheek aangevraagd van <span id=\"telenen-orv\"></span><span id=\"orv-met-nhg\" style=\"display:none;\"> met Nationale Hypotheek Garantie</span>. ";
        echo "Aangezien de hypotheek hoger is dan 80% van de waarde van de woning, moet je dit gedeelte afdekken met een overlijdensrisicoverzekering (orv). ";
        echo "<br />";
        echo "<br />";
        echo "Het minimaal te verzekeren bedrag betreft: <span name=\"orv-bedrag\"></span>. Heb je een partner ingevoerd, dan dient dit bedrag tevens voor de partner te zijn afgedekt. ";
        echo "Heb je al een orv afgesloten?";
        echo "<br />";
        echo "<br />";
        echo "<input type=\"radio\" name=\"orv-ja-nee\" value=\"ja\">Ja<br />";
        echo "<input type=\"radio\" name=\"orv-ja-nee\" value=\"nee\">Nee<br />";
        echo "<div id=\"orv-ja\" style=\"display:none;\">";
            echo "Is het bedrag wat je hebt verzekerd minimaal <span name=\"orv-bedrag\"></span><br />";
            echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-ja-nee\" value=\"ja\">Ja<br />";
            echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-ja-nee\" value=\"nee\">Nee<br />";
            echo "<div id=\"orv-ja-minimaal-bedrag-ja\" style=\"display:none;\">";
                echo "We zullen een kopie polis bij je opvragen nadat de aanvraag bij ons in behandeling is genomen.";
            echo "</div>";
        echo "</div>";
        echo "<div id=\"orv-ja-minimaal-bedrag-nee\" style=\"display:none;\">";
            echo "Hypotheeklijn kan voor jou kijken wat de goedkoopste premie is bij een verzekerd kapitaal van <span name=\"orv-bedrag\"></span> met gelijkblijvende dekking. Wens je dit?<br />";
            echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-nee-wens-ja-nee\" value=\"ja\">Ja<br />";
            echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-nee-wens-ja-nee\" value=\"nee\">Nee<br />";
            echo "<div id=\"orv-ja-minimaal-bedrag-nee-wens-ja\" style=\"display:none;\">";
                echo "Wij verzekeren minimaal het bedrag van <span name=\"orv-bedrag\"></span>, echter kan het zijn dat je meer wilt verzekeren. ";
                echo "In dat geval kan je opgeven hoeveel je wilt verzekeren. Wij zullen je een premievoorstel doen.<br />";
                echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-nee-wens-ja-minimum-bedrag\" value=\"minimum-bedrag\">Ik wil het minimale bedrag verzekeren<br />";
                echo "<input type=\"radio\" name=\"orv-ja-minimaal-bedrag-nee-wens-ja-hoger-bedrag\" value=\"hoger-bedrag\">Ik wil een hoger bedrag verzekeren, namelijk : <br />";
                echo "<input type=\"number\" id=\"hoger-bedrag-verzekeren\" class=\"form-breedte75-procent text_input is_empty\" />";
                echo "<div class=\"first_form form_element form_fullwidth\">";
                    echo "<label for=\"soorthypotheek\">1 of 2 levens verzekeren</label>";
                    echo "<select class=\"form-breedte75-procent text_input is_empty\" id=\"een-of-twee-levens\" />";
                        echo "<option value=\"\"></option>";
                        echo "<option value=\"1\">1</option>";
                        echo "<option value=\"2\">2</option>";
                    echo "</select>";
                echo "</div>";
            echo "</div>";
        echo "</div>";
    echo "</div>";
    
    echo "<input type=\"submit\" class=\"button-primary\" id=\"terug-naar-stap1\" value=\"Terug\" />";
    echo "&nbsp;";
    echo "&nbsp;";
    echo "<input type=\"submit\" class=\"button-primary\" id=\"naar-stap3\" value=\"Naar stap 3\" />";
?>