jQuery(document).ready(function($) { 
    $('#stap1-met-partner-kruis').click(function(){
        $('#stap1-met-partner-help').hide();
        $('#stap1-met-partner-question').show();
    });
    $('#stap1-met-partner-question').click(function(){
        $('#stap1-met-partner-help').show();
        $('#stap1-met-partner-question').hide();
    });
    $('#stap1-studieschuld-kruis').click(function(){
        $('#stap1-studieschuld-help').hide();
        $('#stap1-studieschuld-question').show();
    });
    $('#stap1-studieschuld-question').click(function(){
        $('#stap1-studieschuld-help').show();
        $('#stap1-studieschuld-question').hide();
    });
    $('#stap1-roodstaan-kruis').click(function(){
        $('#stap1-roodstaan-help').hide();
        $('#stap1-roodstaan-question').show();
    });
    $('#stap1-roodstaan-question').click(function(){
        $('#stap1-roodstaan-help').show();
        $('#stap1-roodstaan-question').hide();
    });
    $('#stap1-creditcard-kruis').click(function(){
        $('#stap1-creditcard-help').hide();
        $('#stap1-creditcard-question').show();
    });
    $('#stap1-creditcard-question').click(function(){
        $('#stap1-creditcard-help').show();
        $('#stap1-creditcard-question').hide();
    });
    $('#stap1-partneralimentatie-kruis').click(function(){
        $('#stap1-partneralimentatie-help').hide();
        $('#stap1-partneralimentatie-question').show();
    });
    $('#stap1-partneralimentatie-question').click(function(){
        $('#stap1-partneralimentatie-help').show();
        $('#stap1-partneralimentatie-question').hide();
    });
    $('#stap1-overigeleningen-kruis').click(function(){
        $('#stap1-overigeleningen-help').hide();
        $('#stap1-overigeleningen-question').show();
    });
    $('#stap1-overigeleningen-question').click(function(){
        $('#stap1-overigeleningen-help').show();
        $('#stap1-overigeleningen-question').hide();
    });
    $('#stap2-koopsom-kruis').click(function(){
        $('#stap2-koopsom-help').hide();
        $('#stap2-koopsom-question').show();
    });
    $('#stap2-koopsom-question').click(function(){
        $('#stap2-koopsom-help').show();
        $('#stap2-koopsom-question').hide();
    });
    $('#stap2-overdrachtsbelasting-kruis').click(function(){
        $('#stap2-overdrachtsbelasting-help').hide();
        $('#stap2-overdrachtsbelasting-question').show();
    });
    $('#stap2-overdrachtsbelasting-question').click(function(){
        $('#stap2-overdrachtsbelasting-help').show();
        $('#stap2-overdrachtsbelasting-question').hide();
    });
    $('#stap2-leveringsakte-kruis').click(function(){
        $('#stap2-leveringsakte-help').hide();
        $('#stap2-leveringsakte-question').show();
    });
    $('#stap2-leveringsakte-question').click(function(){
        $('#stap2-leveringsakte-help').show();
        $('#stap2-leveringsakte-question').hide();
    });
    $('#stap2-hypotheekakte-kruis').click(function(){
        $('#stap2-hypotheekakte-help').hide();
        $('#stap2-hypotheekakte-question').show();
    });
    $('#stap2-hypotheekakte-question').click(function(){
        $('#stap2-hypotheekakte-help').show();
        $('#stap2-hypotheekakte-question').hide();
    });
    $('#stap2-taxatie-kruis').click(function(){
        $('#stap2-taxatie-help').hide();
        $('#stap2-taxatie-question').show();
    });
    $('#stap2-taxatie-question').click(function(){
        $('#stap2-taxatie-help').show();
        $('#stap2-taxatie-question').hide();
    });
    $('#stap2-commissie-kruis').click(function(){
        $('#stap2-commissie-help').hide();
        $('#stap2-commissie-question').show();
    });
    $('#stap2-commissie-question').click(function(){
        $('#stap2-commissie-help').show();
        $('#stap2-commissie-question').hide();
    });
    $('#stap2-nhg-kruis').click(function(){
        $('#stap2-nhg-help').hide();
        $('#stap2-nhg-question').show();
    });
    $('#stap2-nhg-question').click(function(){
        $('#stap2-nhg-help').show();
        $('#stap2-nhg-question').hide();
    });
    $('#stap2-eigen-geld-kruis').click(function(){
        $('#stap2-eigen-geld-help').hide();
        $('#stap2-eigen-geld-question').show();
    });
    $('#stap2-eigen-geld-question').click(function(){
        $('#stap2-eigen-geld-help').show();
        $('#stap2-eigen-geld-question').hide();
    });
});
