<?php
    echo "<h3>Werk gegevens</h3>";
    echo "<div id=\"gegevens-indien-loondienst\">";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"beroep\">Beroep/Functie</label><input class=\"form-breedte250\" type=\"text\" id=\"beroep\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"datumindiensttreding\">Datum indiensttreding</label><input class=\"form-breedte250\" type=\"text\" id=\"datumindiensttreding\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"einddatumcontract\">Einddatum contract</label><input class=\"form-breedte250\" type=\"text\" id=\"einddatumcontract\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"naamwerkgever\">Naam werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"naamwerkgever\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"postcodewerkgever\">Postcode werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"postcodewerkgever\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"huisnummerwerkgever\">Huisnummer werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"huisnummerwerkgever\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"straatnaamwerkgever\">Straatnaam werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"straatnaamwerkgever\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"plaatswerkgever\">Plaats werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"plaatswerkgever\" />";
        echo "</div>";
    echo "</div>";
    echo "<div id=\"gegevens-indien-eigen-onderneming\">";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"naam-onderneming\">Naam onderneming</label><input class=\"form-breedte250\" type=\"text\" id=\"naam-onderneming\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"soort-onderneming\">Soort onderneming</label>";
            echo "<select class=\"form-breedte250\" id=\"soort-onderneming\">";
                echo "<option value=\"\"></option>";
                echo "<option value=\"eenmanszaak\">Eenmanszaak</option>";
                echo "<option value=\"vof\">Vennootschap onder Firma</option>";
            echo "</select";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"kvk-nummer\">Kvk-nummer</label><input class=\"form-breedte250\" type=\"text\" id=\"kvk-nummer\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"datum-oprichting\">Datum van oprichting</label><input class=\"form-breedte250\" type=\"text\" id=\"datum-oprichting\" />";
        echo "</div>";
    echo "</div>";
    echo "<h3 id=\"werkgegevens-partner-h3\">Werk gegevens Partner</h3>";
    echo "<div id=\"gegevens-indien-loondienst-partner\">";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"beroep\">Beroep/Functie</label><input class=\"form-breedte250\" type=\"text\" id=\"beroep-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"datumindiensttreding\">Datum indiensttreding</label><input class=\"form-breedte250\" type=\"text\" id=\"datumindiensttreding-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"einddatumcontract\">Einddatum contract</label><input class=\"form-breedte250\" type=\"text\" id=\"einddatumcontract-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"naamwerkgever\">Naam werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"naamwerkgever-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"postcodewerkgever\">Postcode werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"postcodewerkgever-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"huisnummerwerkgever\">Huisnummer werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"huisnummerwerkgever-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"straatnaamwerkgever\">Straatnaam werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"straatnaamwerkgever-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"plaatswerkgever\">Plaats werkgever</label><input class=\"form-breedte250\" type=\"text\" id=\"plaatswerkgever-partner\" />";
        echo "</div>";
    echo "</div>";
    echo "<div id=\"gegevens-indien-eigen-onderneming-partner\">";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"naam-onderneming\">Naam onderneming</label><input class=\"form-breedte250\" type=\"text\" id=\"naam-onderneming-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"soort-onderneming-partner\">Soort onderneming</label>";
            echo "<select class=\"form-breedte250\" id=\"soort-onderneming-partner\">";
                echo "<option value=\"\"></option>";
                echo "<option value=\"eenmanszaak\">Eenmanszaak</option>";
                echo "<option value=\"vof\">Vennootschap onder Firma</option>";
            echo "</select";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"kvk-nummer\">Kvk-nummer</label><input class=\"form-breedte250\" type=\"text\" id=\"kvk-nummer-partner\" />";
        echo "</div>";
        echo "<div class=\"first_form form_element form_fullwidth\">";
            echo "<label for=\"datum-oprichting\">Datum van oprichting</label><input class=\"form-breedte250\" type=\"text\" id=\"datum-oprichting-partner\" />";
        echo "</div>";
    echo "</div>";

    echo "<input type=\"submit\" class=\"button-primary\" id=\"terug-naar-stap5\" value=\"Terug\" />";
    echo "&nbsp;";
    echo "&nbsp;";
    echo "<input type=\"submit\" class=\"button-primary\" id=\"naar-stap7\" value=\"Naar stap 7\" />";
?>