<?php
    echo "<h3>Jouw hypotheekberekening</h3>";
    echo "<table>";
        echo "<tr>";
            echo "<td>Leencapaciteit o.b.v. je financiële situatie</td>";
            echo "<td><span id=\"sidebar-max-hypotheek\">€ 0</span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Leencapaciteit o.b.v. de koopsom</td>";
            echo "<td><span id=\"sidebar-max-hypotheek-koopsom\">€ 0</span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td colspan=\"2\"><hr /></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Jouw hypotheek wordt</td>";
            echo "<td><span id=\"telenen-sidebar\">€ 0</span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Bruto maandlast</td>";
            echo "<td><span id=\"brutomaandlast-sidebar\">€ 0</span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Netto maandlast (eerste maand)</td>";
            echo "<td><span id=\"nettomaandlast-sidebar\">€ 0</span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td colspan=\"2\"><hr /></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Rentepercentage</td>";
            echo "<td><span id=\"rentepercentage-sidebar\">0</span>%</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Rentevaste periode</td>";
            echo "<td><span id=\"rentevasteperiode-sidebar\">10</span> jaar</td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Soort hypotheek</td>";
            echo "<td><span id=\"soorthypotheek-sidebar\"><span></td>";
        echo "</tr>";
        echo "<tr>";
            echo "<td>Nationale Hypotheek Garantie</td>";
            echo "<td><span id=\"nhg-sidebar\">Nee</span></td>";
        echo "</tr>";
    echo "</table>";
?>